name: CI/CD develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]
        mongodb-version: [4.4]

    steps:
      - uses: actions/checkout@v2

      - name: Set Python versions
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Set MongoDB server versions
        uses: supercharge/mongodb-github-action@1.4.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover tests/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@master
    - name: Set Python versions
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt
        pip install wheel
    - name: Make distributable file
      run: |
        python setup.py bdist_wheel
        ls -l dist
    - name: Copy distributable file via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DEV }}
        username: ${{ secrets.USERNAME_DEV }}
        port: ${{ secrets.PORT_DEV }}
        key: ${{ secrets.KEY_DEV }}
        source: "config.py,.python-version,requirements.txt,dist/zlapi-*.whl"
        target: ${{ secrets.TARGET_DEV }}
